apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: instavote
  resourceVersion: "2193"
  uid: 870ae7de-dcd8-4999-b5bb-f03384fec6b2
spec:
  clusterIP: 10.96.206.21
  clusterIPs:
  - 10.96.206.21
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
